<?php
/**
 * Generated by eXtal
 */

namespace Library\ApplicationComponent\Database;

class eUser implements DaoInterface {

	const ID = 'id';
	const USER_ID = 'user_id';
	const OTHER = 'other';

	private $_id;
	private $_user_id;
	private $_other;

	public function id(){
		return $this->_id;
	}

	public function setId($id){
		$this->_id = $id;
	}

	public function user_id(){
		return $this->_user_id;
	}

	public function setUser_id($user_id){
		$this->_user_id = $user_id;
	}

	public function other(){
		return $this->_other;
	}

	public function setOther($other){
		$this->_other = $other;
	}

	public function __construct(){
		// TODO: Implement toString() method.
	}

	public function toString(){
		// TODO: Implement toString() method.
	}

	public static function doSelect($sql){
		// TODO: Implement toString() method.
	}

	public static function retrieveByPk($id){
		// TODO: Implement toString() method.
	}

	public function save(){
		// TODO: Implement toString() method.
	}

	public function delete(){
		// TODO: Implement toString() method.
	}
}