<?php
/**
 * Generated by eXtal
 */

namespace Library\ApplicationComponent\Database;

class eUser implements DaoInterface {

	const ID = 'id';
	const FIRSTNAME = 'firstname';
	const LASTNAME = 'lastname';
	const USERNAME = 'username';
	const PASSWORD = 'password';

	private $_id;
	private $_firstname;
	private $_lastname;
	private $_username;
	private $_password;

	public function id(){
		return $this->_id;
	}

	public function setId($id){
		$this->_id = $id;
	}

	public function firstname(){
		return $this->_firstname;
	}

	public function setFirstname($firstname){
		$this->_firstname = $firstname;
	}

	public function lastname(){
		return $this->_lastname;
	}

	public function setLastname($lastname){
		$this->_lastname = $lastname;
	}

	public function username(){
		return $this->_username;
	}

	public function setUsername($username){
		$this->_username = $username;
	}

	public function password(){
		return $this->_password;
	}

	public function setPassword($password){
		$this->_password = $password;
	}

	public function __construct(){
		// TODO: Implement toString() method.
	}

	public function toString(){
		// TODO: Implement toString() method.
	}

	public static function doSelect($sql){
		// TODO: Implement toString() method.
	}

	public static function retrieveByPk($id){
		// TODO: Implement toString() method.
	}

	public function save(){
		// TODO: Implement toString() method.
	}

	public function delete(){
		// TODO: Implement toString() method.
	}
}