<?php
/**
 * Generated by eXtal
 * Date: 04/08/13
 * Time: 01:03
 */

namespace Application\OneTry\Models\DAO\Base;

class baseOther {

	// **********************
	// CONST DECLARATION
	// **********************
	const ID = 'id';
	const USER_ID = 'user_id';
	const OTHER = 'other';

	// **********************
	// ATTRIBUTE DECLARATION
	// **********************
	protected $_id;
	protected $_user_id;
	protected $_other;

	// **********************
	// CONSTRUCTOR METHOD
	// **********************
	public function __construct(){
		// TODO: Implement toString() method.
	}

	// **********************
	// ACCESSOR METHODS
	// **********************
	public function id(){
		return $this->_id;
	}

	public function setId($id){
		$this->_id = $id;
	}

	public function user_id(){
		return $this->_user_id;
	}

	public function setUser_id($user_id){
		$this->_user_id = $user_id;
	}

	public function other(){
		return $this->_other;
	}

	public function setOther($other){
		$this->_other = $other;
	}


	// **********************
	// TO STRING METHOD
	// **********************
	public function toString(){
		// TODO: Implement toString() method.
	}

	// **********************
	// SELECT METHOD / LOAD ALL
	// **********************
	public static function doSelect($sql){
		// TODO: Implement toString() method.
	}

	// **********************
	// RETRIEVE BY PRIMARY KEY
	// **********************
	public static function retrieveByPk($id){
		// TODO: Implement toString() method.
	}

	// **********************
	// SAVE
	// **********************
	public function save(){
		// TODO: Implement toString() method.
	}

	// **********************
	// DELETE
	// **********************
	public function delete(){
		// TODO: Implement toString() method.
	}

}