<?php
/**
 * Generated by eXtal
 * Date: 04/08/13
 * Time: 09:27
 */

namespace Applications\OneTry\Models\ORM\Base;

use Applications\OneTry\Models\ORM\eUsers;
use Library\Application;

class baseUsers {

	// **********************
	// CONST DECLARATION
	// **********************
	const TABLE = 'users';

	const ID = 'id';
	const FIRSTNAME = 'firstname';
	const LASTNAME = 'lastname';
	const USERNAME = 'username';
	const PASSWORD = 'password';

	// **********************
	// ATTRIBUTE DECLARATION
	// **********************
	protected $id;
	protected $firstname;
	protected $lastname;
	protected $username;
	protected $password;

	// **********************
	// CONSTRUCTOR METHOD
	// **********************
	public function __construct($id = null, $firstname = null, $lastname = null, $username = null, $password = null){
		$this->id = $id;
		$this->firstname = $firstname;
		$this->lastname = $lastname;
		$this->username = $username;
		$this->password = $password;
	}

	// **********************
	// ACCESSOR METHODS
	// **********************
	public function id(){
		return $this->id;
	}

	public function setId($id){
		$this->id = $id;
	}
	public function firstname(){
		return $this->firstname;
	}

	public function setFirstname($firstname){
		$this->firstname = $firstname;
	}
	public function lastname(){
		return $this->lastname;
	}

	public function setLastname($lastname){
		$this->lastname = $lastname;
	}
	public function username(){
		return $this->username;
	}

	public function setUsername($username){
		$this->username = $username;
	}
	public function password(){
		return $this->password;
	}

	public function setPassword($password){
		$this->password = $password;
	}

	// **********************
	// SELECT METHOD / LOAD ALL
	// **********************
	public static function doSelect($sql, $param = array()){
		$stmt = Application::instance()->pdo()->mysql()->prepare($sql);
		$stmt->execute($param);
		return $stmt->fetchAllObjectOfClass("eUsers");
	}

	// **********************
	// RETRIEVE BY PRIMARY KEY
	// **********************
	/**
	 * @return eUsers
	 */
	public static function retrieveByPk($id){
		$stmt = Application::instance()->pdo()->mysql()->prepare("SELECT * FROM users WHERE id = ?");
		$stmt->execute(array($id));
		return $stmt->fetchObjectOfClass("eUsers");
	}

	// **********************
	// INSERT
	// **********************
	public function insert(){
		$stmt = Application::instance()->pdo()->mysql()->prepare("INSERT INTO users (id, firstname, lastname, username, password) VALUES (?, ?, ?, ?, ?);");
		$stmt->execute(array($this->id, $this->firstname, $this->lastname, $this->username, $this->password));
	}

	// **********************
	// UPDATE
	// **********************
	public function update(){
		$stmt = Application::instance()->pdo()->mysql()->prepare("UPDATE users SET firstname = ?, lastname = ?, username = ?, password = ?  WHERE id = ?;");
		$stmt->execute(array($this->firstname, $this->lastname, $this->username, $this->password, $this->id));
	}

	// **********************
	// DELETE
	// **********************
	public function delete(){
		$stmt = Application::instance()->pdo()->mysql()->prepare("DELETE FROM users WHERE id = ?;");
		$stmt->execute(array($this->id));
	}

}