<?php
/**
 * Generated by eXtal
 * Date: 04/08/13
 * Time: 11:20
 */

namespace Applications\OneTry\Models\ORM;

use Applications\OneTry\Models\ORM\Base\baseOther;

class eOther extends baseOther {

}